apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-hry359
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hry359
  namespace: my-nginx-hry359
  labels:
    name: nginx-hry359
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-hry359
  template:
    metadata:
      namespace: my-nginx-hry359
      labels:
        name: nginx-hry359
    spec:
      containers:
      - name: nginx-hry359
        image: nginx
        ports:
        - containerPort: 80

